### ISSUE TITLE
angular 5.0.0-alpha+4 compability

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/angular_analyzer_plugin#494]
No analysis of angular code performed when using angular 5.0.0-alpha+4, analyser 0.31.0-alpha.2 and SDK 2.0.0-dev.20.0
OS: Windows 10
IDE: Webstorm 2017.3 Build 173.4548.30

analysis_options.yaml:
```
analyzer:
  strong-mode: true
  plugins:
    angular:
      enabled: true
```

pubspec.yaml:
```
environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4
  angular_components: ^0.9.0-alpha+3

dev_dependencies:
  angular_analyzer_plugin: ^0.0.12 # <-- not sure if this is required?

dependency_overrides:
  analyzer: ^0.31.0-alpha.2
```
