### ISSUE TITLE
Dart 2 Issues (if you experience general issues with the plugin comment here)

### ISSUE THREAD

**Issue by manuscle** [dart-lang/angular_analyzer_plugin#618]
Hi, I open a new issue here because #602 still not working for me
I've deleted ~/.dartServer/.plugin_manager
Then I've restarted WebStorm :
![image](https://user-images.githubusercontent.com/596562/44075592-9a9e58c4-9f9d-11e8-912d-74578a6ccf69.png)

The following result from the command line :
```
$ /usr/lib/dart/bin/pub run bin/plugin.dart 
Unhandled exception:
NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(SendPort)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      new PluginIsolateChannel (package:analyzer_plugin/src/channel/isolate_channel.dart:109:15)
#2      Driver.start (package:analyzer_plugin/src/driver.dart:30:40)
#3      start (package:angular_analyzer_plugin/starter.dart:14:8)
#4      main (file:///home/manu/.dartServer/.plugin_manager/33cbfe83eac30f8a2acdc2fa0aeecc3f/analyzer_plugin/bin/plugin.dart:7:3)
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:275:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```
The result from the Dart server :

```
Status
Preview-dart-2: true
Use fasta parser: false
Use common front end: false
Instrumentation enabled: false
Server process ID: 11233
Versions
Analysis server version: 1.20.3
Dart SDK: 2.0.0 (Unknown timestamp) on "linux_x64"

No exceptions encountered!

Analysis plugins
angular-5.0.0
bootstrap package path: /home/manu/.pub-cache/hosted/pub.dartlang.org/angular-5.0.0/tools/analyzer_plugin

execution path: /home/manu/.dartServer/.plugin_manager/33cbfe83eac30f8a2acdc2fa0aeecc3f/analyzer_plugin/bin/plugin.dart

packages file path: /home/manu/.dartServer/.plugin_manager/33cbfe83eac30f8a2acdc2fa0aeecc3f/analyzer_plugin/.packages

name: Angular Analysis Plugin

version: 1.0.0-alpha.0

Associated contexts:

/home/manu/www/tutos/angular_tour_of_heroes
```
analysis_options.yaml:
```
analyzer:
  exclude: [build/**]
  errors:
    uri_has_not_been_generated: ignore
  plugins:
    - angular

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unnecessary_const
    - unnecessary_new
    - unrelated_type_equality_checks
    - valid_regexps
```

Please let me know if you need more details
